Added askSelection function and created framework for groups

diff --git a/scripts/install2 b/scripts/install2
--- a/scripts/install2
+++ b/scripts/install2
@@ -29,7 +29,13 @@ function askModule {
 
     if [ "$(checkModule 'WITH_DIALOG')" ]; then
 
-        # Do not stop exec on non 0 return values
+               set +e
+        # shellcheck disable=SC2086
+        dialog $dialogGlobalParams $dialogParam --title "$2" --yesno "Install $2?" 6 55
+        response=$?
+        # Return to previous setting
+        set -e
+ # Do not stop exec on non 0 return values
         set +e
         # shellcheck disable=SC2086
         dialog $dialogGlobalParams $dialogParam --title "$2" --yesno "Install $2?" 6 55
@@ -69,6 +75,69 @@ function checkModule {
         echo "1"
     else
         echo ""
+    fi
+}
+
+# Ask user to choose from a selection of items
+# list is \n delimited list in formation "x text"
+# where x is the single character selection that is returned
+#    askSelection <list> <message> <default>
+# result is stored in dialogReply
+dialogREPLY=""
+function askSelection {
+
+    selection=$1
+    dialogREPLY=""
+    default="$3"
+    if [ "$(checkModule 'WITH_DIALOG')" ]; then
+        # Do not stop exec on non 0 return values
+
+        selection=$(echo -e "$selection" | while read -r selected; do
+                    selectedItem="${selected:0:1}"
+                    selectedText="${selected:2}"
+                    if [[ "${selected:0:1}" == "$default" ]]; then
+                        echo "$selectedItem \"$selectedText\" on"
+                    else
+                        echo "$selectedItem \"$selectedText\" off"
+                    fi
+            done)
+        echo $selection > /tmp/selectionList
+
+        # shellcheck disable=SC2086
+        dialog $dialogGlobalParams --radiolist "$2" 10 55 4  --file /tmp/selectionList 2> /tmp/res
+        rm -f selectionList
+        response=$(cat /tmp/res)
+        rm -f /tmp/res
+        # Return to previous setting
+
+        if [[ "$response" == "" ]]; then
+            exit 1
+        fi
+        dialogREPLY="$response"
+    else
+        isValid=""
+        while [[ "$isValid" == "" ]]; do
+
+            echo "$2"
+            echo -------------------
+            echo -e "$1"
+            echo -------------------
+            read -p "Selection:  " -n 1 -r
+            echo ""
+            if [[ "$REPLY" == "" ]] && [[ "$default" != "" ]]; then
+                REPLY="$default"
+                isValid=1
+            else
+                REPLY=$(echo "$REPLY" | awk '{print toupper($0)}')
+
+                isValid=$(echo -e "$selection" | while read -r selected; do
+                    if [[ "${selected:0:1}" == "$REPLY" ]]; then
+                        echo 1
+                    fi
+                done)
+            fi
+        done
+        dialogREPLY="$REPLY"
     fi
 }
 
@@ -155,6 +224,7 @@ else
     fi
 fi
 
+
 echo -e "\e[1;32mStarting installation on ${BOARD_FAMILY} ${BOARD_NAME} (${BOARD_REVISION})...\e[0m"
 
 # Normalize OS environment
@@ -192,6 +262,48 @@ askModule "WITH_DIALOG" "Text User Interface?" "n"
 if [ "$(checkModule 'WITH_DIALOG')" ]; then
     sudo apt-get install dialog -y
 fi
+
+askSelection "a Basic node\nb Pi Stream\nz Custom" "Select install type" z
+case $dialogREPLY in
+    a)
+        echo "Basic node"
+        WITH_MESH_POINT=true
+        WITH_WIFI_AP=""
+        WITH_FIREWALL=""
+        WITH_CJDNS_IPTUNNEL=true
+        WITH_IPFS=false
+        WITH_PROMETHEUS_NODE_EXPORTER=true
+        WITH_PROMETHEUS_SERVER=false
+        WITH_GRAFANA=false
+        WITH_EXTRA_TOOLS="
+        WITH_WATCHDOG=""
+        WITH_YRD=""
+        WITH_SSB=false
+        WITH_SSB_WEB=false
+        WITH_IPFS_PI_STREAM=false
+    ;;
+    b)
+        WITH_MESH_POINT=true
+        WITH_WIFI_AP=true
+        WITH_FIREWALL=""
+        WITH_CJDNS_IPTUNNEL=true
+        WITH_IPFS=true
+        WITH_PROMETHEUS_NODE_EXPORTER=""
+        WITH_PROMETHEUS_SERVER=false
+        WITH_GRAFANA=false
+        WITH_EXTRA_TOOLS=""
+        WITH_WATCHDOG=""
+        WITH_YRD=""
+        WITH_SSB=true
+        WITH_SSB_WEB=true
+        WITH_IPFS_PI_STREAM=true
+    ;;
+    z)
+    ;;
+    *)
+        echo "Error unknown response $dialogREPLY"
+        exit
+    ;;
 
 # Prompt and set missing flags
 
